### ISSUE TITLE
Bad links in documentation 

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/mgt-samples#17]
### Sample

MGT-person

### Author(s)

no idea

### Suggestion

 the links here seems to be wrong : https://pnp.github.io/mgt-samples/samples/mgt-person/

### Are you willing to help?

Yes

**Comment by sebastienlevert** [comment]
I don't think this site should be used anymore. @hugoabernier can we turn it off in favor of the Adoption Gallery?

**Comment by hugoabernier** [comment]
@sebastienlevert done. You may want to point the aka.ms (if any) to redirect

**Comment by sebastienlevert** [comment]
@hugoabernier closed this site, so we should be in business! Closing.
