### ISSUE TITLE
Integration with asp.net core SSO with Single Tenant SPN

### ISSUE THREAD

**Issue by ellio246t** [pnp/mgt-samples#9]
### Sample

https://github.com/pnp/mgt-samples/tree/main/samples/app/msal2provider-asp-net-core-sso

### Author(s)

@sebastienlevert

### What happened?

I have followed the instructions in the sample with two deviations:

1. My SPN is a single tenant SPN
2. The client secret is not in app.config

The sdk controls never manage to display data from AAD and appear as empty or with a message no data found.
How can I get this to work with a single tenant SPN

### App Registration
Here are the app permissions:
![image](https://github.com/pnp/mgt-samples/assets/22543355/81584505-450e-48f9-95b1-02b1e417e554)

### Client Secret
This is supplied in Program.cs after retrieving from key vault.  SSO is working fine:
var secretClient = new SecretClient(new Uri(builder.Configuration.GetValue<string>("KeyVault:VaultUri")), new DefaultAzureCredential());
var clientSecret = secretClient.GetSecret(builder.Configuration.GetSection("AzureAD").GetValue<string>("ApplicationName"));
var initialScopes = builder.Configuration["DownstreamApi:Scopes"]?.Split(' ') ?? builder.Configuration["MicrosoftGraph:Scopes"]?.Split(' ');

builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
             .AddMicrosoftIdentityWebApp(microsoftIdentityOptions =>
             {
                 microsoftIdentityOptions.ClientId = builder.Configuration.GetSection("AzureAd").GetValue<string>("ClientId");
                 microsoftIdentityOptions.Domain = builder.Configuration.GetSection("AzureAd").GetValue<string>("Domain");
                 microsoftIdentityOptions.TenantId = builder.Configuration.GetSection("AzureAd").GetValue<string>("TenantId");
                 microsoftIdentityOptions.Instance = builder.Configuration.GetSection("AzureAd").GetValue<string>("Instance");
                 microsoftIdentityOptions.CallbackPath = builder.Configuration.GetSection("AzureAd").GetValue<string>("CallbackPath");
                 microsoftIdentityOptions.ClientSecret = clientSecret.Value.Value;
                 microsoftIdentityOptions.GetClaimsFromUserInfoEndpoint = true;
             })
             .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
             .AddMicrosoftGraph(builder.Configuration.GetSection("MicrosoftGraph"))
             .AddInMemoryTokenCaches();
### MSAL2 Provider Initialization
This is happening in _layout.cshtml

@if (User.Identity.IsAuthenticated)
        {
            
            
            <script src="https://unpkg.com/@@microsoft/mgt@3/dist/bundle/mgt-loader.js"></script>
            <script>
                mgt.Providers.globalProvider = new mgt.Msal2Provider({
                    clientId: "@Configuration["AzureAd:ClientId"]",
                    loginHint: "@User.Claims.FirstOrDefault(c => c.Type == "preferred_username")?.Value",
                    redirectUri: "/sso.html",
                    authority: "https://login.microsoftonline.com/@Configuration["AzureAd:TenantId"]"
                    loginType: mgt.LoginType.Popup
                });
            </script>
        }
If I inspect the html I see this the the header:

<script src="https://unpkg.com/@microsoft/mgt@3/dist/bundle/mgt-loader.js"></script>
--
  | <script>
  | mgt.Providers.globalProvider = new mgt.Msal2Provider({
  | clientId: "aa1c150d-0ab5-44ee-b1b3-48150574f0d1",
  | loginHint: "Philip.Elliott@**********.com",
  | redirectUri: "/sso.html",
  | authority: "https://login.microsoftonline.com/********-My-TenantId"
  | loginType: mgt.LoginType.Popup
  | });
  | </script>

### SSS.html
This is added to wwwroot.

### Steps to reproduce

1. Follow the tutorial as per above
2.Add this to the home page @if (User.Identity.IsAuthenticated)
    {
        <div>Signed in User: <mgt-person person-query="me" view="oneline"></mgt-person></div>

        <mgt-people-picker></mgt-people-picker>
        
    }
3. Observe that no data from AAD is displayed.

### Expected behavior

I expect to see the logged on user details and be able to search and pick users from AAD.
This is what I see:
![image](https://github.com/pnp/mgt-samples/assets/22543355/c43c475d-192d-4e9c-9a30-200375f6c6f8)

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

asp.net core MVC web application hosted in Azure PaaS web app.  Here's the project defintion:
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.6.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.16.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="1.16.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="System.Collections.NonGeneric" Version="4.3.0" />
  </ItemGroup>

</Project>

**Comment by sebastienlevert** [comment]
Can you provide a small repro that we could test it out? That would help us identify the right issues. Thanks! Also adding @gavinbarron as he's been the one fiddling around with this sample!

**Comment by gavinbarron** [comment]
Oh wow, you were so close to having this working @ellio246t 

You're missing a comma at the end of the authority line where you set up the provider in the _Layout.cshtml and that's breaking your SSO flow.

When looking at the network requests in the browser your should see a chain of requests out to the login.microsoft.com site and redirecting back to the sso page if you have a valid config for your provider.

Additionally you should see any errors in the query string for the request to the sso page.

**Comment by ellio246t** [comment]
Thanks for your responses gentlemen.  I fixed the missing comma but that must be issue 1 of N, the behaviour was unchanged.  I've run a network trace and could see the chain of requests just as you described. SS0.html is called but the token request has failed:
![image](https://github.com/pnp/mgt-samples/assets/22543355/c6783c08-2bfb-4e0f-9d64-8056721d53e7)

I've created a stripped down version of the app I can share.  If you fill in the app.config file and sort the client secret in program.cs it should run.  
[Web.zip](https://github.com/pnp/mgt-samples/files/12559745/Web.zip)

**Comment by ellio246t** [comment]
Hi
I investigated the bad request error some more.  The actual error is:
AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'https://localhost:7267'.
Trace ID: 6c70a7b3-a32e-41bc-8ade-882a242a0f00
Correlation ID: 9a858aed-9c1f-4a85-9c34-84951069aabb
Timestamp: 2023-09-13 07:40:57Z

So it seems the issue is to do the application registration but what specifically? I already mentioned that the app I'm using is configured as a single tenant app and that is the only thing (I know of) that deviates from the code sample instructions.  Will the SDK work with a single tenant app registration and if so how do I configure it?

**Comment by gavinbarron** [comment]
When you register the app in AAD and add the redirect uri for the SSO page
you must add it as the SPA type. It sounds like you might have added it as
the web type.

**Comment by gavinbarron** [comment]
The authentication blade of the app registration should look like this: 
![Screenshot of the Authentication blade in AAD for an app registration](https://github.com/pnp/mgt-samples/assets/7122716/c7781e3f-0b2c-4f37-96c4-feef149de405)

**Comment by ellio246t** [comment]
I added a platform for SPO and now I can see the controls have started to work:
![image](https://github.com/pnp/mgt-samples/assets/22543355/e152d318-1795-4d2f-bc72-ae554653ff10)

This is real progress.  Thankyou so much!  

I still have one final question for you:
In the image I am being prompted to ask my AD admin to approve API permissions.  Read Presence of All users isn't granted yet but view user basic profile is.  What is going on here?  Is this more missing app registration config?  I don't want users of the web app to see such prompts, how do I fix it?

**Comment by sebastienlevert** [comment]
To avoid users seeing this prompt, you'll have to do a global admin consent like here: https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent?pivots=portal. This will approve the set of permissions you need for all the users in your tenant.

**Comment by ellio246t** [comment]
Is this in addition to the consent that has already been granted on app
registration?  Seems crazy this is required twice.

**Comment by gavinbarron** [comment]
The mechanics of app consent are not something we have control over. MGT is a user of the AAD/Entra services and we just have to live with their rules, I suspect what is happening here is that the admin is being asked to consent for all the requested scopes for the application, not just the additional one that requires admin approval.

As the integration between the sample and the single tenant application is now resolved I think we can close this issue. Please do re-open it, or raise a new issue if there are additional issues you face.
